### PR TITLE
drawArrow, utils filder and drawPolygon, PolygonArea

### PR DESCRIPTION
**Pull request by kakila**
Simplify code, improve calculation, decouple ration and head type, improve output arguments, extend docs
I have improved this function for Octave. Check the following demo (you might have to adapt it to matlab)

 # Arrow type
 clf;
 orig   = [cumsum(0.5*ones(3,1))-0.5 zeros(3,1)];
 tip    = orig + [0 1];
 arrows = [orig tip];

 # Different ratios
 subplot (2,1,1)
 r = [0.8 0.5 0.1];
 h = drawArrow (arrows, 1, 0.1, r);
 title ('Ratios (3rd argument)')
 text (tip(:,1)+0.1,tip(:,2)-0.5,arrayfun(@num2str, r,'UniformOutput', 0))

 # Different types
 subplot (2,1,2)
 ht = [0 0.5 1];
 h = drawArrow (arrows, 1, 0.1 , 0.1, ht);
 title ('Head types (4th argument)')
 text (tip(:,1)+0.1,tip(:,2)-0.5,arrayfun(@num2str, ht,'UniformOutput', 0))

### CODE REVIEW

**Comment by dlegland** [comment]
Hi,
thanks for pull request.
I'm abroad for a while, hope to complete the merge by the end of th week.

**Comment by kakila** [comment]
Added some more changes.
1. Moved a utility function "isAxisHandle" to an "utils" folder. If you knwo more of these functions please move them there.
2. There is a student working for GNU Octave under GSoC who is improving polygon functions. I just went through drawPolygon and improved what I could. This will make the introduction of future changes more easily

Please do check the new drawPolygon. I wrote some test suits for Octave, you might want to run them https://sourceforge.net/p/octave/geometry/ci/950ef04724ac9f6fbade537b3ee0285e1fd7fb11/tree/inst/polygons2d/drawPolygon.m line 140 and later.

**Comment by kakila** [comment]
I have simplified the code of polygonArea and make it handle holes.
You can run the tests below in Matlab  (need to adapt since this is valid Octave)
I also updated the documentation and Bourke's webpage url.

```
%!shared pccw, pcw
%! pccw = pcw = [0 0; 1 0; 1 1; 0 1];
%! pcw([2 4],:) = pcw([4 2], :);

%!assert (polygonArea (1, 0), 0);
%!assert (polygonArea ([1 0 ;1 1]), 0);
%!assert (polygonArea ([1; 1], [0; 1]), 0);

%!assert (polygonArea (pccw), 1);
%!assert (polygonArea (pcw), -1);
%!assert (polygonArea ({pccw;pcw}), [1;-1]);
%!assert (polygonArea ({pccw,pcw}), [1,-1]);

%%!assert (polygonArea([pc; nan(1,2); 0.5*pcw+[0.25 0.25]]), 0.75)
%!test
%! ph = [pccw; nan(1,2); 0.5*pcw+[0.25 0.25]];
%! ph = {ph;ph};
%! assert (polygonArea(ph), [0.75; 0.75])

```

**Comment by dlegland** [comment]
Hi,

your pull request poses some problems, as it introduces octave-specific syntax, and does not follow existing code convention. 
please be consistent with the existing.

**Comment by kakila** [comment]
Hi David,

I always try to be consistent. Could you pint where is the problem, so I can fix it? 
If there is octave specifics, they just slip through. I do not have matlab but nevertheless I try to send you updates that are matlab compatible, I guess you will be happy to try them out.

**Comment by dlegland** [comment]
Hi Kakila,
I had a quick look at the recent modified files, and could notice some problems, or non-homogeneity:
- the "#" comments are not accepted by Matlab
- the use of "eval" (in drawArrow) is usually discouraged. Isn't any other way of writing it ?
- the spacing convention (two spaces) is nt consistent with the existing code (four spaces)
- I usually do not use parens after "if" construct
- the print_usage () function does not exist with matlab, causing a bug at the execution
- concerning the "utils" directory, I try to limit the number of directories, and to give them specific names. Many libraries have a "utils" directory, making it difficult, or at least less easy, to identify where a file comes from. 

I'm happy with the proposals of enhancement. But in this case, I think it will be necessary to re-write a large part of the code... 
I agree that trying to manage code running both for Matlab and Octave would require more care than for one plateform only.

Also, I will try to write a page on the wiki to formalize more clearly the coding conventions used through the library (even if I have to admit I sometimes break them...).

regards,
David

**Comment by kakila** [comment]
Hi D,

Ok, let me fix all that and sorry for the mishaps. 
Regarding "ultils". In the path it will appear as .../matgeom/utils so no way of confusing it with some other package util folder. I mean, since you already introduce folders to keep things tidy, it really doesn't make sense to have isAxesHandle in geom2d! It will be placed in "utils" in Octave's geomtry package.

Damn, matlab doesn't have print_usage? well...let me see, maybe another function for "utils" :smile: 

Re coding conventions: the easiest is to use a convention that already exist. Octave tries to follow the GNU convention  
https://en.wikipedia.org/wiki/GNU_coding_standards
with exceptions
https://www.gnu.org/software/octave/doc/v4.0.0/Octave-Sources-_0028m_002dfiles_0029.html#Octave-Sources-_0028m_002dfiles_0029

my suggestion is that you think "free", beyond matlab.

**Comment by dlegland** [comment]
Hi, 
well, I agree on GNU coding standards for C or C++ languages, but not really for "matlab-like" languages.

I mainly follow the following guidelines 
http://www.mathworks.com/matlabcentral/fileexchange/46056-matlab-style-guidelines-2-0
They are rather widely followed in the matlab community. I will continue base on them.

ok for the "utils" directory. Matlab way of managing dependencies / packages is not great, but this way should do the job.

concerning the "print_usage", there ay be some other functions existing in one language ("platform" ?) and not in the other. Maybe there can be some resources on the net for listing the potential compatibility breaks?

**Comment by kakila** [comment]
Regarding comment:
- the use of "eval" (in drawArrow) is usually discouraged. Isn't any other way of writing it ?

The use of "eval" is discouraged when the string to evaluate comes from the user, i.e. "arbitrary code strings". In this case the string is hard-coded in the function so there is no reason not to evaluate that string. This is to avoid repeating the same code for each of the parameter variables that were called "lwrh", which I just kept from your code. The way I would do this is to store all these values in a matrix, since all of these variables have the same size. Then the code gets even simpler, but harder to follow (will put comments). Shall I do that?

**Comment by kakila** [comment]
Regarding the style. I cannot download it, it requires that I make an account with the mathworks. If I do that I will be breaking their terms of use, because they say that file is download from there are to be used only with Mathworks products. This includes the Guidelines. Are they published somewhere else?

**Comment by kakila** [comment]
I think I have fixed all you requested, please let me know if there is still something missing.

**Comment by dlegland** [comment]
Hi,
great!
Thanks for working on it. I try to check it soon!

**Comment by dlegland** [comment]
guidelines can be found without account:
http://www.ee.columbia.edu/~marios/matlab/MatlabStyle1p5.pdf
I would also recommend the guideline: "Write Programs for People, Not Computers"

**Comment by dlegland** [comment]
I have fixed the remaining issues, by trying to find the best wompromise between your modifs and matlab compatibility. I hope this will fit your needs.

**Comment by kakila** [comment]
Sure, I am just doing this so you can profit from our developments. I do not use matGeom but its Octave port :smile: . You could also totally ignore all this, just let me know so I do not waste my time.

I will check the guidelines to be aware of them.

**Pull request merged**
