### PR TITLE
added function cutFacesOffMesh.m

### PR DESCRIPTION
**Pull request by oqilipo**

### CODE REVIEW

**Comment by oqilipo** [comment]
Function to cut faces off a mesh by a logical index into the faces of the mesh.

**Comment by dlegland** [comment]
Hi,
what about the name "removeMeshFaces" for this function? t would be more consistent with similar functions, and for "container" view of a mesh. Tell me if this suits you, or if you have other naming conventions in mind.
best,

**Comment by oqilipo** [comment]
Yes, you're right. I'm going to change it.
kind regards

**Comment by oqilipo** [comment]
And the output should be a new mesh:
- without the faces of the logical index
- only the faces of the logical index
?

**Comment by oqilipo** [comment]
To test removeMeshFaces.m:

```
clearvars; close all

[vertices, faces] = createSoccerBall;
m.vertices=vertices;
faces = triangulateFaces(faces);
m.faces=faces;
fLI = false(length(faces),1);
rmFI=round(linspace(1,length(faces),10))
fLI(rmFI)=true;

faceCents = faceCentroids(vertices, faces);

%% 
[vertices2, faces2] = removeMeshFaces(vertices, faces, fLI);
assert(isequal(faceCentroids(vertices, faces(~fLI,:)),faceCentroids(vertices2, faces2)))

figure('color','w')
drawMesh(vertices, faces, 'faceColor', 'none', 'faceAlpha', .2);
drawMesh(vertices2, faces2, 'faceAlpha', .7);
text(faceCents(fLI,1),faceCents(fLI,2),faceCents(fLI,3),num2str(rmFI'))
view(3)
axis equal

%% 
[m2] = removeMeshFaces(vertices, faces, fLI);
assert(isequal(faceCentroids(vertices, faces(~fLI,:)),faceCentroids(m2.vertices, m2.faces)))

figure('color','w')
drawMesh(vertices, faces, 'faceColor', 'none', 'faceAlpha', .2);
drawMesh(m2.vertices, m2.faces, 'faceAlpha', .7);
text(faceCents(fLI,1),faceCents(fLI,2),faceCents(fLI,3),num2str(rmFI'))
view(3)
axis equal

%%
[m2] = removeMeshFaces(m, fLI);
assert(isequal(faceCentroids(m.vertices, m.faces(~fLI,:)),faceCentroids(m2.vertices, m2.faces)))

figure('color','w')
drawMesh(vertices, faces, 'faceColor', 'none', 'faceAlpha', .2);
drawMesh(m2.vertices, m2.faces, 'faceAlpha', .7);
text(faceCents(fLI,1),faceCents(fLI,2),faceCents(fLI,3),num2str(rmFI'))
view(3)
axis equal

```

**Comment by oqilipo** [comment]
To test cutMeshByPlane.m:

```
clearvars; close all

% cut a soccerball by a plane
[v, f] = createSoccerBall;
f = triangulateFaces(f);
mesh.vertices=v; mesh.faces=f;
planeOrigin = [-0.2 0 0];
planeNormaL = [-1 0 -1];
plane = createPlane(planeOrigin, planeNormaL);

%%
[above, inside, below] = cutMeshByPlane(mesh, plane);

figure('color','w'); axis equal; hold on; view(3)
drawMesh(above, 'FaceColor', 'r');
drawMesh(inside, 'FaceColor', 'g');
drawMesh(below, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
[aV, aF, iV, iF, bV, bF] = cutMeshByPlane(mesh.vertices, mesh.faces, plane);

figure('color','w'); axis equal; hold on; view(3)
drawMesh(aV, aF, 'FaceColor', 'r');
drawMesh(iV, iF, 'FaceColor', 'g');
drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
[aV, aF] = cutMeshByPlane(mesh.vertices, mesh.faces, plane,'part','above');

figure('color','w'); axis equal; hold on; view(3)
drawMesh(aV, aF, 'FaceColor', 'r');
% drawMesh(iV, iF, 'FaceColor', 'g');
% drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
[iV, iF] = cutMeshByPlane(mesh.vertices, mesh.faces, plane,'part','in');

figure('color','w'); axis equal; hold on; view(3)
% drawMesh(aV, aF, 'FaceColor', 'r');
drawMesh(iV, iF, 'FaceColor', 'g');
% drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
[bV, bF] = cutMeshByPlane(mesh.vertices, mesh.faces, plane,'part','below');

figure('color','w'); axis equal; hold on; view(3)
% drawMesh(aV, aF, 'FaceColor', 'r');
% drawMesh(iV, iF, 'FaceColor', 'g');
drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
above = cutMeshByPlane(mesh, plane,'part','above');

figure('color','w'); axis equal; hold on; view(3)
drawMesh(above, 'FaceColor', 'r');
% drawMesh(iV, iF, 'FaceColor', 'g');
% drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
inside = cutMeshByPlane(mesh, plane,'part','in');

figure('color','w'); axis equal; hold on; view(3)
% drawMesh(aV, aF, 'FaceColor', 'r');
drawMesh(inside, 'FaceColor', 'g');
% drawMesh(bV, bF, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)

%%
below = cutMeshByPlane(mesh, plane,'part','below');

figure('color','w'); axis equal; hold on; view(3)
% drawMesh(aV, aF, 'FaceColor', 'r');
% drawMesh(iV, iF, 'FaceColor', 'g');
drawMesh(below, 'FaceColor', 'b');

drawPlane3d(plane, 'FaceAlpha',.7)
drawVector3d(planeOrigin, planeNormaL)
```

**Comment by dlegland** [comment]
merged!
By the way, you can set yourself of the new functions you are creating!

**Comment by dlegland** [comment]
I have updated the Comments files, and transformed your test files into demo scripts. Like this it is easy to run them again. (they are in the "demos" folder).

**Pull request merged**
