### PR TITLE
Vectorization

### PR DESCRIPTION
**Pull request by kakila**
This function was optimized in its GNU Octave version. I am porting the changes to matGeom.
Would you like to add a GNU Octave branch to your repo?

### CODE REVIEW

**Comment by dlegland** [comment]
Hi,
I have created the branch and merged modifs.

**Comment by kakila** [comment]
Perfect, I will be committing the GNU Octave code to that branch asap.

**Comment by kakila** [comment]
btw, these two branches will be unmergeable.

**Comment by dlegland** [comment]
Hmm, in this case it would make sense to have two distinct projects, no ? I had the impression that branches were for developments that had to be integrated when they're ready. Another solution could be to create sub projects, it seems to be possible for large projects.

**Comment by kakila** [comment]
Yes, I think you are right. Another option is to have a subfolder "MatGeom_Octave" or something of the sort.
I am not familiar with subprojects, if you think that's better then go ahead.
Let me know what you decide. If you think another repository is the best option, then I could make one (we already have one still in sf, but a github backup is not a bad idea)

**Pull request merged**
