### PR TITLE
Fixed readMesh.m. Added name-value pair if path is required in the struct.

### PR DESCRIPTION
**Pull request by oqilipo**

### CODE REVIEW

**Comment by oqilipo** [comment]
Hi David

Can you approve approve the pull request. Otherwise it is always necessary to remove the fields "name" & "filePath" before using other mesh functions with the mesh struct.

Kind regards

**Comment by dlegland** [comment]
hi,
and sorry for delay;
actually I do not get the point of this PR: I do not see why it is a problem to have more fields than necessary in the result struct. On the contrary, I find it more useful, at least to get some meta data on the mesh (here the name), and/or to be able to read additional info such as normals or anything else.
So I am in favor of rejecting.

**Comment by oqilipo** [comment]
Hi David

The update of adding the two fields "name" & "filePath" automatically on default did broke some of my old code.
For example it creates an error in "concatenateMeshes"
That's why I added it as optional using a name-value pair.

Would be great if we could use this option to ensure backward compatibility.

Kind regards

**Comment by dlegland** [comment]
I understand,
but in this case why not update the code in `concatenateMeshes`? I have quickly checked, and  (at least for this file) it seems that it is only necessary to intervert the role of the two inputs of the `ismember` function [on lines 33-34](https://github.com/mattools/matGeom/blob/1661b32e2005113abbd53affbd186ea7a8f49102/matGeom/meshes3d/concatenateMeshes.m#L33).

The objective of the readMesh/write functions, when I originally write them, was to facilitate input/output of meshes, by trying to be generic about file format and data representation(s). Forcing only two fields is a strong limitation, and does not improve a lot compare to using two separate output arguments (which is also possible with most functions).

Also, allowing more fields makes it possible to enhance the behaviour of the library (e.g., management of normals, of vertex-face relationships, or many other things).

**Comment by oqilipo** [comment]
Hi David

Makes sense for me. I'm not sure if other mesh functions are affected, too. I close the pull request and you can adapt concatenateMeshes.

Kind regards

**Pull request closed without merging**
